// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDILy-qAWHxgRmZTpQVa7ICWN6uG-xvQ',
    appId: '1:552366389754:web:1ea1f50d53d1d78d118c43',
    messagingSenderId: '552366389754',
    projectId: 'selfdiary-e99a7',
    authDomain: 'selfdiary-e99a7.firebaseapp.com',
    storageBucket: 'selfdiary-e99a7.appspot.com',
    measurementId: 'G-6Z9Q0S9BZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ld5nri5qmOlRk04TNZ7VUdq-mJJFP-4',
    appId: '1:552366389754:android:a715101ce4536d0b118c43',
    messagingSenderId: '552366389754',
    projectId: 'selfdiary-e99a7',
    storageBucket: 'selfdiary-e99a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Tjn_pWegYcDZS9kOZa6Awyi3TjSmHX0',
    appId: '1:552366389754:ios:3770866f4f25ec18118c43',
    messagingSenderId: '552366389754',
    projectId: 'selfdiary-e99a7',
    storageBucket: 'selfdiary-e99a7.appspot.com',
    androidClientId: '552366389754-g0omtfh61rm642fqavu0t38riet1pfok.apps.googleusercontent.com',
    iosClientId: '552366389754-u0me98o4acbsajk1frh2t9774brpfal6.apps.googleusercontent.com',
    iosBundleId: 'com.glowingcactus.selfdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Tjn_pWegYcDZS9kOZa6Awyi3TjSmHX0',
    appId: '1:552366389754:ios:5a7e47351133d01e118c43',
    messagingSenderId: '552366389754',
    projectId: 'selfdiary-e99a7',
    storageBucket: 'selfdiary-e99a7.appspot.com',
    androidClientId: '552366389754-g0omtfh61rm642fqavu0t38riet1pfok.apps.googleusercontent.com',
    iosClientId: '552366389754-p7llbrgmlao5cd0tq489c78rf4j8jotv.apps.googleusercontent.com',
    iosBundleId: 'com.glowingcactus.selfdiary.RunnerTests',
  );
}
